name: 'analytics_dev'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  analytics_dev:
    silver:
      +schema: SILVER
      +materialized: table

    gold:
      +schema: GOLD
      +materialized: table

vars:
  holiday_country_code: 'US'
  start_date: '2023-01-01'
  end_date: '2029-12-31'